sonar.projectKey=ecommerce-backend
sonar.projectName=ecommerce-Backend
sonar.sources=app
sonar.tests=tests
sonar.language=php
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=sqp_f2b8ae609248f2958984a49782abfdfcc171dd34
        
